/*
NabooApi V1

Here you have the first version of the naboo api to create checkout automatically

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package naboo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteTransactionResponse{}

// DeleteTransactionResponse struct for DeleteTransactionResponse
type DeleteTransactionResponse struct {
	OrderId string `json:"order_id"`
	Message string `json:"message"`
}

type _DeleteTransactionResponse DeleteTransactionResponse

// NewDeleteTransactionResponse instantiates a new DeleteTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteTransactionResponse(orderId string, message string) *DeleteTransactionResponse {
	this := DeleteTransactionResponse{}
	this.OrderId = orderId
	this.Message = message
	return &this
}

// NewDeleteTransactionResponseWithDefaults instantiates a new DeleteTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteTransactionResponseWithDefaults() *DeleteTransactionResponse {
	this := DeleteTransactionResponse{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *DeleteTransactionResponse) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *DeleteTransactionResponse) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *DeleteTransactionResponse) SetOrderId(v string) {
	o.OrderId = v
}

// GetMessage returns the Message field value
func (o *DeleteTransactionResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DeleteTransactionResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DeleteTransactionResponse) SetMessage(v string) {
	o.Message = v
}

func (o DeleteTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order_id"] = o.OrderId
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *DeleteTransactionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order_id",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteTransactionResponse := _DeleteTransactionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteTransactionResponse)

	if err != nil {
		return err
	}

	*o = DeleteTransactionResponse(varDeleteTransactionResponse)

	return err
}

type NullableDeleteTransactionResponse struct {
	value *DeleteTransactionResponse
	isSet bool
}

func (v NullableDeleteTransactionResponse) Get() *DeleteTransactionResponse {
	return v.value
}

func (v *NullableDeleteTransactionResponse) Set(val *DeleteTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteTransactionResponse(val *DeleteTransactionResponse) *NullableDeleteTransactionResponse {
	return &NullableDeleteTransactionResponse{value: val, isSet: true}
}

func (v NullableDeleteTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


