/*
NabooApi V1

Here you have the first version of the naboo api to create checkout automatically

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package naboo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAllTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllTransaction{}

// GetAllTransaction struct for GetAllTransaction
type GetAllTransaction struct {
	Transactions []GetOneTransaction `json:"transactions"`
}

type _GetAllTransaction GetAllTransaction

// NewGetAllTransaction instantiates a new GetAllTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllTransaction(transactions []GetOneTransaction) *GetAllTransaction {
	this := GetAllTransaction{}
	this.Transactions = transactions
	return &this
}

// NewGetAllTransactionWithDefaults instantiates a new GetAllTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllTransactionWithDefaults() *GetAllTransaction {
	this := GetAllTransaction{}
	return &this
}

// GetTransactions returns the Transactions field value
func (o *GetAllTransaction) GetTransactions() []GetOneTransaction {
	if o == nil {
		var ret []GetOneTransaction
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *GetAllTransaction) GetTransactionsOk() ([]GetOneTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *GetAllTransaction) SetTransactions(v []GetOneTransaction) {
	o.Transactions = v
}

func (o GetAllTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactions"] = o.Transactions
	return toSerialize, nil
}

func (o *GetAllTransaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAllTransaction := _GetAllTransaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAllTransaction)

	if err != nil {
		return err
	}

	*o = GetAllTransaction(varGetAllTransaction)

	return err
}

type NullableGetAllTransaction struct {
	value *GetAllTransaction
	isSet bool
}

func (v NullableGetAllTransaction) Get() *GetAllTransaction {
	return v.value
}

func (v *NullableGetAllTransaction) Set(val *GetAllTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllTransaction(val *GetAllTransaction) *NullableGetAllTransaction {
	return &NullableGetAllTransaction{value: val, isSet: true}
}

func (v NullableGetAllTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


